[project]
name = "me-stow"
version = "0.1.0"
description = "Simple configuration files management that use symlink (like gnu stow) but with some changes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
